### PR TITLE
Added DIP, CN, AGT (Ongoing)

### PR DESCRIPTION
**Pull request by smit2k14**

### CODE REVIEW

**Review by statebait — APPROVED** [review]
LGTM

**Review by Kartikeya99 — CHANGES_REQUESTED** [review]
Remove the .vscode folder and the ipynb checkpoints and add them to the .gitignore

**Review by Kartikeya99 — CHANGES_REQUESTED** [review]
IE/404(IT472)_digital_image_processing/manish_khare/2020/assignments/assignment_1/Untitled.ipynb

rename this untitled.

**Review by gauravsofat — APPROVED** [review]
LGTM pending one minor change as suggested by @Kartikeya99 
Once done, please merge this PR and create new ones for further additions/changes. Doesn't make sense to have an open PR which is in an _ongoing_ state.

**Review by Tikam02 — APPROVED** [review]

**Comment by gauravsofat** [comment]
Following up, when are we closing this?

**Comment by smit2k14** [comment]
Don't quite want to close this, quite a bit more stuff is left

**Comment by gauravsofat** [comment]
> Don't quite want to close this, quite a bit more stuff is left

Consider merging it for now, and create more frequent granular PRs instead?

**Review by Kartikeya99 — APPROVED** [review]

**Review by statebait — APPROVED** [review]

**Pull request merged**
