### PR TITLE
Add resources - meet59patel

### PR DESCRIPTION
**Pull request by meet59patel**
Added CS-Arnab Ray-2018 resources

### CODE REVIEW

**Comment by smit2k14** [comment]
Don't add the stuff that the course instructor already uploads. If you have some other stuff, like the lab codes or the lab assignments PDF or handwritten notes that are different than those of the prof, add those.

**Review by smit2k14 — CHANGES_REQUESTED** [review]
Don't add the stuff that the course instructor already uploads. If you have some other stuff, like the lab codes or the lab assignments PDF or handwritten notes that are different than those of the prof, add those.

**Comment by meet59patel** [comment]
@smit2k14  Got it. 
I've uploaded content referring to and equivalent to [CS/201_introductory_computational_physics/bhaskary_chaudhary/2017](https://github.com/Tikam02/AcadVault/tree/master/CS/201_introductory_computational_physics/bhaskary_chaudhary/2017)
Shall I close the PR if none of these files are required?

**Comment by smit2k14** [comment]
Eyo... on second thoughts, keep the lecture slides as they were. We talked over it, and it might turn out helpful. Sorry for the confusion.

**Review by smit2k14 — APPROVED** [review]
Works right now.

**Review by Kartikeya99 — APPROVED** [review]

**Review by gauravsofat — APPROVED** [review]

**Pull request merged**
