### PR TITLE
Kartikeya99

### PR DESCRIPTION
**Pull request by Kartikeya99**
Added the complete acad folder

### CODE REVIEW

**Review by smit2k14 — APPROVED** [review]
Lage to barabar j che. Works for me

**Comment by statebait** [comment]
> Lage to barabar j che. Works for me

Please avoid using Gujarati here 🤣

**Review by statebait — CHANGES_REQUESTED** [review]
Why is a lab_sessions folder in root?

**Review by statebait — APPROVED** [review]

**Review by gauravsofat — APPROVED** [review]
Everything looks great. A minor typo I noticed was with the faculty name for SC220. Approving this PR, but if you could correct that spelling it would be great. 
Otherwise we can address that in future commits.
P.S Please Squash and Merge.

**Pull request merged**
