### PR TITLE
Add resources tikam02

### PR DESCRIPTION
**Pull request by Tikam02**
7th-Semester Resources forwarded by @JalanshMunshi 
CT-425
IE-402
IT-477
SC-322

### CODE REVIEW

**Review by gauravsofat — CHANGES_REQUESTED** [review]
All looks good, but there is an error wrt SC322 — Files that should have been part of  `/SC/322_graph_theory/rahul_muthu/2019/...`, have currently been added to `/SC/322_graph_theory/rahul_muthu/lecture_notes/2019/...`

**Comment by Tikam02** [comment]
@gauravsofat deleted Namra's notes from directory that's been on both directories.

**Comment by Tikam02** [comment]
While uploading through frontend the problem of duplicate files will be taken care.
Although right now we can't tackle this problem.

**Review by gauravsofat — APPROVED** [review]
Thanks for the quick fixes and unfiltered commit messages @smit2k14

**Comment by smit2k14** [comment]
Always a pleasure @gauravsofat

**Pull request merged**
