### PR TITLE
Add resources hitgo00

### PR DESCRIPTION
**Pull request by hitgo00**

### CODE REVIEW

**Comment by smit2k14** [comment]
Please follow the guidelines given in README before creating a PR. Folder names are not proper.

**Comment by hitgo00** [comment]
sorry_my_bad;
missed_the_🐍!

**Review by smit2k14 — CHANGES_REQUESTED** [review]
The format is 
Prof Name 
 -- Year

and not prof_name_year

Check it out in EL and a couple of other places

**Comment by hitgo00** [comment]
done ✅

**Review by smit2k14 — CHANGES_REQUESTED** [review]
In SC107, the lecture notes are not in a folder. Create a folder for that. Other stuff seems fine to me. Also, now that you are changing stuff, can you also put your c-t111 project in a folder with your name? Folder name should be either your ID or your name in small with snake case, for example either 201801xxx or hitesh_goyal

**Comment by hitgo00** [comment]
aye aye captain!

**Review by smit2k14 — APPROVED** [review]

**Comment by gauravsofat** [comment]
@all-contributors please add @hitgo00 for content

**Pull request merged**
