### PR TITLE
Sem5 papers and Blockchain course

### PR DESCRIPTION
**Pull request by Avi-Patel**
i was messed up from my side while removing capital letters(caps locks). So i deleted that pull request and creating new fresh one. Please have a look :)

### CODE REVIEW

**Review by smit2k14 — APPROVED** [review]
Haha no issues. Everything LGTM :+1:  

Edit: one change added below

**Review by smit2k14 — CHANGES_REQUESTED** [review]
remove desktop.ini in assignments. forgot to mention that

**Comment by Avi-Patel** [comment]
> remove desktop.ini in assignments. forgot to mention that

done 👍

**Review by Tikam02 — APPROVED** [review]

**Review by smit2k14 — APPROVED** [review]

**Review by statebait — APPROVED** [review]

**Review by Kartikeya99 — APPROVED** [review]
LGTM. Merging

**Comment by Kartikeya99** [comment]
sem5 papers and blockchain course

**Pull request merged**
