### PR TITLE
HPC - 2015 Lecture notes

### PR DESCRIPTION
**Pull request by Tikam02**
HPC  lecture notes from 3 different sources + Insem 2 paper with answer sheet

### CODE REVIEW

**Review by gauravsofat — CHANGES_REQUESTED** [review]
Please organise lecture notes and papers into separate folders (i.e `lecture_notes` and `exam_papers` respectively) as per the [directory structure](https://github.com/Tikam02/AcadVault#directory-structure) in the README. Everything else looks good to go!

**Comment by Tikam02** [comment]
Cool I'll make changes

**Comment by Tikam02** [comment]
moved question papers to misc

**Comment by Tikam02** [comment]
@gauravsofat organized file, review it.

**Review by gauravsofat — APPROVED** [review]

**Pull request merged**
