### PR TITLE
Add resources meet59patel

### PR DESCRIPTION
**Pull request by meet59patel**
- [x] Add Resources of `CS374, CT303, IE402, IT304, IT214`

### CODE REVIEW

**Comment by smit2k14** [comment]
LGTM

**Review by smit2k14 — APPROVED** [review]

**Review by statebait — APPROVED** [review]
LGTM!

**Review by Kartikeya99 — APPROVED** [review]

**Review by Tikam02 — APPROVED** [review]

**Comment by smit2k14** [comment]
Merge if there are no issues?

**Comment by meet59patel** [comment]
image

**Pull request merged**
