### PR TITLE
Added hand written notes of EHD 

### PR DESCRIPTION
**Pull request by NeelMakadiya14**

### CODE REVIEW

**Review by Tikam02 — APPROVED** [review]

**Review by statebait — CHANGES_REQUESTED** [review]
File should go in `lecture_notes`

**Review by gauravsofat — APPROVED** [review]
LGTM pending changes suggested by @statebait

**Review by Kartikeya99 — APPROVED** [review]
Thanks for contributing! Just make the change as suggested by @statebait

**Comment by gauravsofat** [comment]
@NeelMakadiya14 just following up on this.

**Comment by statebait** [comment]
Merging this for now since the author is not replying. We can move the file in a separate maintenance PR.

**Comment by statebait** [comment]
@all-contributors please add @NeelMakadiya14 for Content

**Pull request merged**
