### PR TITLE
Add SC209 environmental studies

### PR DESCRIPTION
**Pull request by abhinavraj23**

### CODE REVIEW

**Review by gauravsofat — CHANGES_REQUESTED** [review]
Hi @abhinavraj23, thanks for the PR. This is a new addition and we definitely want to add it to the repo. That being said, we cannot accept the PR in its current form as it does not follow the [directory structure](https://github.com/Tikam02/AcadVault#directory-structure) as laid out in the README.

Requesting you to modify this PR according to the [directory structure](https://github.com/Tikam02/AcadVault#directory-structure) and re-request a review.  Feel free to reply to this thread if you need any help.

Thanks!

**Comment by abhinavraj23** [comment]
@gauravsofat I have made the changes

**Comment by smit2k14** [comment]
Are these your notes? If yes, the year is supposed to be the batch (2017) in our case. sorry if the readme didn't make that clear. Also, I guess change the spelling of Ranendu and while you're at it, also change the spelling of jaydip to jaydeep. Baki stuff looks fine I guess

**Comment by abhinavraj23** [comment]
@smit2k14 all changes done, I have even added the .gitignore file.

**Review by smit2k14 — APPROVED** [review]

**Review by gauravsofat — APPROVED** [review]
LGTM. Thanks @abhinavraj23

**Comment by gauravsofat** [comment]
@all-contributors please add @abhinavraj23 for content

**Pull request merged**
